name: flutter_debounce_throttle_riverpod_example
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.0.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ">=2.6.0 <4.0.0"
  flutter_debounce_throttle_riverpod:
    path: ../
  flutter_lints: ^6.0.0
  flutter_driver:
    sdk: flutter
dev_dependencies:
  test: ^1.30.0
